[package]
name = "appflowy-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
actix-http = "3.3.1"
actix-rt = "2"
actix-web-actors = { version = "4.2.0" }
actix-service = "2.0.2"
actix-identity = "0.5.2"
actix-cors = "0.6.4"

# serde
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde-aux = "4.1.2"

tokio = { version = "1.26.0", features = [
    "macros",
    "rt-multi-thread",
    "sync",
    "fs",
    "time",
] }
futures-util = "0.3.26"
async-stream = "0.3.4"
jsonwebtoken = "8.2.0"
config = { version = "0.13.3", default-features = false, features = ["yaml"] }
once_cell = "1.13.0"
chrono = { version = "0.4.23", features = ["serde"] }
derive_more = {version = "0.99"}

# tracing
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.16", features = ["registry", "env-filter", "ansi", "json"] }
tracing-bunyan-formatter = "0.3.6"
tracing-actix-web = "0.7"
tracing-log = "0.1.1"

ormx = { version = "0.10.0", features = ["postgres"]}
[dependencies.sqlx]
version = "0.5.9"
default-features = false
features = [
    "postgres",
    "runtime-actix-native-tls",
    "macros",
    "uuid",
    "chrono",
    "migrate",
    "offline",
]

[[bin]]
name = "appflowy_server"
path = "src/main.rs"


[lib]
path = "src/lib.rs"