[package]
name = "http-flowy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
thiserror = "1.0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
bytes = { version = "1.0", features = ["serde"]}
derive_more = {version = "0.99", features = ["display"]}
uuid = { version = "0.8", features = ["v4"] }
protobuf = {version = "2.18.0"}

reqwest = {version = "0.11", optional = true}
hyper = {version = "0.14", optional = true }
actix-web = {version = "4.0.0-beta.8", optional = true }

[features]
with_reqwest = ["reqwest", "hyper"]
with_actix_web = ["actix-web"]