application:
  port: 8000
  host: 0.0.0.0
  server_key: ""
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "appflowy_pg"
redis_uri: "redis://127.0.0.1:6379"
